# 发布新版本的 CI

name: release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ release ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: env
        run: echo $GITHUB_WORKSPACE

      # Runs a single command using the runners shell
      - name: cmake generate
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && cmake ..

      - name: cmake build
        run: cd $GITHUB_WORKSPACE/build && cmake --build . --config Release

      - name: ls
        run: cd $GITHUB_WORKSPACE/build && pwd && ls -alh

      - name: Linux重命名文件
        if: runner.os == 'Linux'
        run: mv /home/runner/work/demo_c/demo_c/build/demo_c /home/runner/work/demo_c/demo_c/build/${{ matrix.os }}demo_c

      - name: 发布 Linux 二进制文件
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /home/runner/work/demo_c/demo_c/build/${{ matrix.os }}demo_c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
